# Form implementation generated from reading ui file 'main_dlg.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Maindlg(object):
    def setupUi(self, Maindlg):
        Maindlg.setObjectName("Maindlg")
        Maindlg.setWindowModality(QtCore.Qt.WindowModality.NonModal)
        Maindlg.resize(825, 565)

        self.retranslateUi(Maindlg)
        QtCore.QMetaObject.connectSlotsByName(Maindlg)

    def retranslateUi(self, Maindlg):
        _translate = QtCore.QCoreApplication.translate
        Maindlg.setWindowTitle(_translate("Maindlg", "密码生成器"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Maindlg = QtWidgets.QDialog()
    ui = Ui_Maindlg()
    ui.setupUi(Maindlg)
    Maindlg.show()
    sys.exit(app.exec())
